# Generated by Django 3.0.2 on 2020-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/', verbose_name='uploaded image'),
        ),
    ]
