# Generated by Django 3.0.2 on 2020-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200326_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='confirmed_image',
            field=models.ImageField(blank=True, null=True, upload_to='confirmed_images/', verbose_name='confirmed image'),
        ),
    ]
