// Authentication
export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const STORE_AUTH_ERROR = 'STORE_AUTH_ERROR';
export const SET_IS_FIRST_TIME_USER = 'SET_IS_FIRST_TIME_USER';
export const SET_NOT_FIRST_TIME_USER = 'SET_NOT_FIRST_TIME_USER';

// Password reset
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const STORE_RESET_ERROR = 'STORE_RESET_ERROR';

// Invitation
export const STORE_INVITATION_ERROR = 'STORE_INVITATION_ERROR';
export const REMOVE_INVITATION_ERROR = 'REMOVE_INVITATION_ERROR';

// Registration validation
export const STORE_REGISTRATION_ERROR = 'STORE_REGISTRATION_ERROR';
export const REMOVE_REGISTRATION_ERROR = 'REMOVE_REGISTRATION_ERROR';

// Images
export const STORE_SELECTED_IMAGE = 'STORE_SELECTED_IMAGE';
export const STORE_UPLOAD_AND_PREDICTIONS = 'STORE_UPLOAD_AND_PREDICTIONS';
export const STORE_LOCATION = 'STORE_LOCATION';
export const STORE_PREDICTION_CONFIRMATION = 'STORE_PREDICTION_CONFIRMATION';
export const STORE_IMAGE_TAKING_METHOD = 'STORE_IMAGE_TAKING_METHOD';
export const CLEAR_IMAGES_STATE = 'CLEAR_IMAGES_STATE';

// Network
export const SET_NETWORK_ERROR = 'NETWORK_ERROR';
export const CLEAR_NETWORK_ERROR = 'CLEAR_NETWORK_ERROR';
export const SET_NETWORK_SUCCESS = 'SET_NETWORK_SUCCESS';
export const CLEAR_NETWORK_SUCCESS = 'CLEAR_NETWORK_SUCCESS';

// Status bar
export const SHOW_STATUS_BAR = 'SHOW_STATUS_BAR';
export const HIDE_STATUS_BAR = 'HIDE_STATUS_BAR';
