# Generated by Django 3.0.2 on 2020-01-23 14:40

from django.db import migrations


def populate_db(apps, schema_editor):
    # Admin Notifications
    notification_types = [
        {
            "key": "new_user_registered",
            "subject": "Subject: A new User has registered",
            "title": "Title: A new User has registered",
            "description": "Description: A new User has registered",
            "template": "Email: {{ email }}"
        },
        {
            "key": "user_reset_password",
            "subject": "Subject: A User reset his password.",
            "title": "Title: A User reset his password.",
            "description": "Tittle: A User reset his password.",
            "template": "Password reset for: {{ email }}"
        },
    ]
    NotificationType = apps.get_model('notifications', 'NotificationType')
    for notification_type in notification_types:
        NotificationType(**notification_type).save()


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0002_notificationprofile_user'),
        # ('users', '0002_data_migration'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
